mysite/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    #path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),name="login"),
    path('logout/', auth_views.LogoutView.as_view(),name="logout"),
    path('signup/', views.signUp,name="signup"),
    path('<int:pk>/', views.AccountPage.as_view(), name='account_detail'),
    path("accept/<int:pk>/",views.AcceptContact.as_view(),name="accept_request"),
    path("reject/<int:pk>/",views.RejectContact.as_view(),name="reject_request"),
    path("delete/<int:pk>/",views.DeleteContact.as_view(),name="delete_contact"),
    path('', views.loginUser,name='login2'),
    path('login/', views.loginUser,name='login2'),
    path('search/', views.searchAccount,name='search'),


]

mysite/chat/urls.py
# chat/urls.py
from django.urls import path

from . import views
app_name = 'chat'

urlpatterns = [
    path('', views.meetings, name='meetings'),
    path('dev', views.dev, name='dev'),

]

mysite/mysite/urls.py
# mysite/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin

urlpatterns = [
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls',namespace="accounts")),
    path('', include('django.contrib.auth.urls')),
]

mysite/templates/__templates-admin.html
<div id="checkbox-basic" class="list-group-item rounded-0" style='background-color: #eeeeee'>
  <input class="group-input form-check-input me-1 checkbox" type="checkbox" style="float:left">
  <div class="body"></div>
</div>

<div id="button-basic" class="list-group-item" style='background-color: #eeeeee' input type="submit">
  <div class="body"></div>
</div>

<div id="container-justify-between">
  <div class="body d-flex justify-content-between"></div>
</div>

<div id="container-left">
  <div class="body d-flex align-items-center"></div>
</div>

<div id="container-center">
  <div class="body d-flex justify-content-center"></div>
</div>

<div id="container-float-right">
  <div class="body" style="float:right;"></div>
</div>

<div id="username">
</div>

<div id="seen">
</div>

<div id="empty-container">
  <div class="body"></div>
</div>

<div id="text-field">
  <div class="body"></div>
</div>


<button id="options2" class="m-1 btn btn-white border border-1 options%" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="true" aria-controls="collapseExample">...</button>






<!-- header options -->
<div id="options-body2" class="d-flex justify-content-end border-1"  style="position: fixed; z-index: 4; width: 180px; top:103px; right: 16px; " onclick="stopProp(event)">
  <div class="collapse sub" id="collapseExample">
      <div class="d-flex justify-content-end">
          <div class="card card-body p-0" style=" background-color: #eeeeee; max-height: calc(100vh - 65px); overflow:auto;">
              <div id="chat-nav-container-top"></div>
              <div class="body"></div>
          </div>
      </div>
    </div>
</div>
<!-- end header options -->
<!-- menu admin -->



<div id="submit-selected" class="border border-1" type="button" style="width: 100%; background-color: #eeeeee">
<div class="body"></div>
</div>

<div id="spinner" class="spinner-border spinner-border-sm" role="status" style="position:absolute"></div>



<label id="checkbox-content-item" class="list-group-item rounded-0 checkboxItem%%%" style='background-color: #eeeeee'>
  <input id="remove-content-username-select" class="remove-admin-input group-input form-check-input me-1 checkbox%%" type="checkbox" style="float:left">
  <div id="checkbox-content-username" class="value%"></div>
</label>

<label id="checkbox-createGroup" class="list-group-item rounded-0 checkboxItem%%%" style='background-color: #eeeeee'>
  <input id="remove-content-username-select" class="remove-admin-input group-input form-check-input me-1 checkbox%%" type="checkbox" style="float:left">
  <div class="d-flex justify-content-between">
    <div id="checkbox-content-username" class="value%"></div>
    <div class="lastSeen-hook%"></div>
  </div>
</label>


<!--  end menu admin  -->

mysite/templates/__templates-search.html
<!-- search page inactive -->
    <div class="d-flex align-items-center justify-content-center contentHeight" id="search-page-inactive">



      <div class="mb-3 w-50">

      <div class="d-flex  align-items-center" style="height: 48px;">
      <input type="email" class="form-control" id="search-input" placeholder="Username">
      <button class="btn btn-primary" id="search-submit" type="submit" onclick="search()" style="margin-left: 5px;">Search</button>
    </div>
    </div>
      <div id="search-content-container" type="text">
        <ul id="search-content-list"></ul>
      </div>

  </div>

    <!-- end search page inactive -->




    <!-- search page active -->
    <div class="contentHeight" id="search-page-active">
        <!-- search page header -->
        <div class="container-fluid right-top-fixed-md border-bottom border-bottom w-100" style="background-color: white;">
            <div class="d-flex align-items-center p-1 col-12 col-md-6">
                <input type="email" class="form-control" id="search-input" placeholder="Username">
                <button class="btn btn-primary" id="search-submit" type="submit" onclick="search()" style="margin-left: 5px;">Search</button>
            </div>
        </div>
        <!-- end search page header -->

        <!-- search page body -->
        <div class="chat-log-messages p-3 " style="overflow: auto; height: calc(100vh - 103px); bottom: 0px;">
              <!-- search page result -->
              <div class="rounded-1 col-12 col-md-6 p-0" id="search-content-container" type="text">
                  <div class="list-group" id="search-content-list"></div>
              </div>
              <!-- end search page result -->
        </div>
        <!-- search page body -->

    </div>
    <!-- end search page active -->

    <!-- search result -->
    <div id="search-content-item" class="d-flex justify-content-between align-items-center list-group-item" style="background-color: white;">
          <div id="search-content-username" style="width: 100%;  overflow:hidden;"></div>
          <div id="result-options" style="margin-left: 10px;"></div>
    </div>
    <!-- end search result -->


    <!-- search result options -->
    <!-- friend -->
    <div id="search-result-options-contact">
          <input class="btn btn-outline-primary btn-sm" id="search-content-username-remove" type="button" value="Remove contact" onclick="removeContact(this,'search')">
    </div>
    <!-- not friend -->
    <div id="search-result-options">
          <input class="btn btn-outline-primary btn-sm" id="search-content-username-add" type="button" value="Add contact" onclick="addContact(this)">
    </div>
    <!-- end search result option -->

mysite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Meetings!</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>
<body>


  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">{{ user }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'accounts:login2' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Sign up</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>







{% block body_block %}

    {% endblock %}

  </body>
</html>

mysite/templates/templates.html
<style>
  #templates{
    display: none
  }

  .chat-log-messages{
    color: #abb2bf;
    position:absolute;
    bottom:0px;
    right:0px;
    left:0px;
    padding-bottom: 15px;
    overflow-y:auto;
    max-height:100%;

  }

  .vertical-aligned{
    margin: 0;
    position: absolute;
    top: 50%;
    -ms-transform: translateY(-50%);
    transform: translateY(-50%);
  }





</style>



<div id="templates">

<!-- user -->

<!-- end user -->



<div id="user-title" class="d-flex align-items-center username%%" style="white-space: nowrap;  overflow:hidden;">
  <div class="username%" style="margin-right: 5px;"></div>
  <div class="ltsn%" style="margin-right: 15px;"></div>
</div>


<div id="chat-header" class="right-top-fixed-md border-bottom header%" style=" background-color:red; z-index: 5; ">
  <div class="container-fluid d-flex justify-content-between align-items-center body">
  </div>
</div>




<!-- keep -->
  <div id="chat-nav-bottom-active">
    <div class="container-fluid p-0 m-0" style="position: absolute;  bottom: 0px;">
      <div id="typing-container" class="body" style=" background-color: #eeeeee"><div class="typing-container-suffix%"></div></div>


    </div>
  </div>
<!-- keep -->

<!-- keep -->
<textarea class="form-control rounded-1 input-field" id="chat-input" t rows="2" id="chat-input" input type="submit" style="resize: none;""></textarea>
<!-- keep -->


<!-- keep -->
<textarea class="form-control rounded-1 input-field" id="search-input" t rows="1" id="chat-input" input type="submit" style="resize: none; overflow-y:hidden;"></textarea>
<!-- keep -->






        <div>
          <input class="btn btn-primary btn-sm" disabled id="chat-submit" type="button" value="Send" onclick="send(this)" style="margin-left: 10px;">
        </div>

<!-- chat  -->
<div class="contentHeight chat-content%" id="chat-content">

<div class="body"></div>

</div>


<!-- keep -->
<div id="chat-log-container" >
  <div id="chat-load-messages-container" >
  </div>
  <div class="container-fluid pt-2 pb-2 ">
    <div id="chat-log-list" class="body" ></div>
    </div>
    <div class="container-fluid">
      <div class="fs-6 p-2" id="chat-typing" style="color: black; "></div>
    </div>
</div>
<!-- keep -->

<button class="btn border border-1 action%%%" id="button" type="button" style="width: 100%;">
<div class="displayName"></div>
</button>


<button class="btn border border-1 action%%%" id="contactListButton" type="button" style="width: 100%;">
<div class="d-flex justify-content-between">
  <div class="ps-2 displayName"></div>
  <div class="pe-2">
    <small><div class="lastSeen-hook">Status</div></small>
    <div class="menu-hook"></div>
  </div>
</div>
</button>
<!-- regular button -->

<div class="dropdown" id="dropdown">
  <a class="btn btn-secondary dropdown-toggle btn-sm" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
    more
  </a>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
  </ul>
</div>

<li id="dropdown-item"><a class="dropdown-item">a</a></li>



  <div id="group-chat-nav-bottom-inactive">
    <ul id="invite-content-list"></ul>
    </div>

    <div id="group-chat-nav-top-inactive">
        <input id="chat-close" type="button" value="Delete" onclick="deleteGroup(this)">

    </div>


<div id="group-chat-nav-top-left">
    <input class="btn border border-1" id="chat-close" type="button" value="Delete" onclick="deleteGroup(this)" style="width: 100%;">
</div>

<!-- group top navigation -->
<div id="group-chat-nav-top-active">
  <input class="btn border border-1" id="chat-close" type="button" value="Delete" onclick="deleteGroup(this)" style="width: 100%;">
  <input class="btn border border-1" id="chat-leave" type="button" value="Leave group" onclick="leaveGroup(this)" style="width: 100%;">
</div>
<!-- end group top navigation -->

<!-- admin top navigation -->
<div id="group-chat-nav-top-active-admin">
  <div id="admin-menu">

  </div>
  <input class="btn border border-1" id="chat-close" type="button" value="Delete" onclick="deleteGroup(this)" style="width: 100%;">
  <input class="btn border border-1" id="chat-leave" type="button" value="Leave group" onclick="leaveGroup(this)" style="width: 100%;">
</div>
<!-- ebd admin top navigation -->


{% include '__templates-admin.html' %}

<div class="menu%%%" id="menu">
</div>


<div id="empty">
  <div id="body">
</div>

<!-- accordion -->
<div class="accordion" id="accordion">

</div>
<!-- end accordion -->

<!-- accordion item -->
    <div class="accordion-item " id="accordion-item">
      <h2 class="accordion-header accordion-header%%" id="makeAdmin">
        <button class="accordion-button admin-button accordion-button%%" id="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse" aria-expanded="false" aria-controls="collapse" style="background-color: #e6e6e6"">
        </button>
      </h2>
      <div id="collapse" class="accordion-collapse collapse collapse%%" aria-labelledby="" data-bs-parent="#accordion" style="background-color: #eeeeee">
        <div class="accordion-body list-group p-0" id="accordion-body"></div>
        <div id="accordion-items"></div>

        <div id="accordion-footer"></div>
      </div>

    </div>
<!-- end accordion item -->







<div id="typing-user-container" class="info%% d-flex align-items-center me-1">
<div id="typing-username" class="pk% username%%"></div>
<div id="typing-seperator" class="pk% seperator% seperator%%"></div>
</div>




<!-- input inactive -->
<div id="chat-nav-bottom-inactive" >
  <div class="container-fluid" style="background-color: black; position: absolute;  bottom: 0px;">
    <div class="d-flex justify-content-between m-2">
      <textarea class="form-control rounded-1" id="chat-input" t rows="2" disabled id="chat-input" style="resize: none;"></textarea>
      <div>
        <input class="btn btn-primary btn-sm" id="chat-submit" type="button" value="Send" disabled style="margin-left: 10px;">
      </div>
    </div>
  </div>
</div>




<!-- end input inactive -->
<div class="list-group-item d-flex justify-content-between align-items-center p-0 rounded-0 contact-item" id="contact">
    <div class="d-flex align-items-center justify-content-between p-3 action%%%"  id="contacts-content-username-container" style="height: 100%; width: 100%;" onclick="clickButton(this)">
    <div class="p-0 username" style="margin-left:10px;"></div>
      <small class="ltsn%"></small>
    </div>


    <div>
      <button class="btn btn-sm border border-1" id="contacts-content-username-remove" type="button" onclick="click(this)" style="margin-right:10px;">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16" style="color: black; vertical-align: -.125em;">
          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
          <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
        </svg>
      </button>
      </div>
</div>


<!-- group -->
<label class="list-group-item rounded-0 p-4 pt-3 pb-3" id="contactCreateGroup">
  <input  class="group-input form-check-input me-1" type="checkbox" style="float:left">
  <div style="float:left"> g </div>
  <small class="%ltsn" style="float:right;"> ffs </small>
</label>
<!-- end group -->

<div id="tempMenu"></div>


  <!-- contacts -->
  <div class="list-group-item d-flex justify-content-between align-items-center p-0 rounded-0 contact-item" id="contacts-content-item">
      <div class="d-flex align-items-center justify-content-between p-3"  id="contacts-content-username-container" style="height: 100%; width: 100%;" onclick="newGroup(this, 'private', 'contacts')">
      <div class="p-0" id="contacts-content-username" style="margin-left:10px;"></div>
        <small class="ltsn%"></small>
      </div>


      <div>
        <button class="btn btn-sm border border-1" id="contacts-content-username-remove" type="button" onclick="removeContact(this)" style="margin-right:10px;">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16" style="color: black; vertical-align: -.125em;">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
          </svg>
        </button>
        </div>
  </div>
  <!-- end contacts -->


  <!-- private -->
  <label id="private-content-item" class="list-group-item rounded-0" onclick="newGroup(this, 'private')">
    <div id="private-content-username" style="float:left"> </div>
  </label>
  <!-- end private -->

  <!-- group -->
  <label id="group-content-item" class="list-group-item rounded-0 p-4 pt-3 pb-3 group-item">
    <input id="group-content-username-select" class="group-input form-check-input me-1" type="checkbox" style="float:left">
    <div id="group-content-username" style="float:left">  </div>
    <small class="%ltsn" style="float:right;">  </small>
  </label>
  <!-- end group -->




  <!-- chats new message counter -->
  <span class="badge bg-primary rounded-pill" id='counter' style="margin-left: 5px;"></span>
  <!-- end chats new message counter -->

  <!-- total new message counter -->
  <span id="counter-total" class="badge bg-secondary">0</span>

  <!-- navbar-->
  <span id="counter-total-top" class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
    1
  </span>
  <!-- end total new message counter -->





{% include '__templates-search.html' %}


<div id="user-tab-title" class="d-flex align-items-center username%%" style="white-space: nowrap;  overflow:hidden;">
  <div class="username%" style="margin-right: 5px;"></div>
</div>

<!-- right panels -->
<div class="tab-pane" id="nav-pane-group" role="tabpanel" aria-labelledby="nav-tab-group">

</div>
<!-- end right panels -->

<!-- chats -->
<button class="list-group-item rounded-0 chat-tab" id="nav-tab-group" data-bs-toggle="tab" data-bs-target="#nav-pane-group" type="button" role="tab" aria-controls="nav-pane-group" aria-selected="true" onclick="selectGroup(this)">
  <div class="body"></div>
</button>



<button class="list-group-item rounded-0 chat-tab" id="nav-tab-groupb" data-bs-toggle="tab" data-bs-target="#nav-pane-group" type="button" role="tab" aria-controls="nav-pane-group" aria-selected="true" onclick="selectGroup(this)">
  <div class="d-flex w-100 justify-content-between">
   <h5 class="mb-1 d-flex flex-row" id="tab-title" style="overflow:hidden;"></h5>
   <div class="d-flex justify-content-between">
     <small id="message-timestamp" style="white-space: nowrap; margin-left: 10px;">Never</small>

     <div id="counter-holder">
     </div>

   </div>
 </div>

<div class="d-flex align-items-center">
  <div class="latest_message%">No messages</div>
  <div class="typing-container% d-flex align-items-center"><div class="typing-container-suffix% "></div>
</div>




   </div>
</button>
<!-- end chats -->

<div id="panel">
  <div class="body"></div>
</div>

<div id="dropdown-button" style="border: 1px solid; display:block;">
  <div class="body">...</div>
</div>

<div id="dropdown-body" style="border: 0px solid; background-color: purple;">
  <div class="body"></div>
</div>







<div id="flex-box" style="display:flex; align-self: stretch; flex-grow: 1;">
  <div class="body" style="display:flex; align-self: stretch; flex-grow: 1;"></div>
</div>

<div id="flex-box3" style="display:flex; align-self: stretch; flex-grow: 1;">
  <div class="body" style="display:flex; align-self: stretch; flex-grow: 1;">asdf</div>
</div>

<div id="stage">
  <div class="body" style="display:flex; align-items: center; justify-content: center;">asdf</div>
</div>



<div id="flex-grow" style="flex-grow: 1;  border-bottom:dotted 2px black; background-color: red;">
  <div class="body" >Grow</div>
</div>


<div id="message" class="d-flex justify-content-start ">
      <div class="body p-3 pt-2 pb-2 m-2 mb-0 rounded-3 border border-1" style="background-color: white; overflow-wrap: break-word;"></div>
</div>

<div id="message-self" class="d-flex justify-content-end">
      <div class="body p-3 pt-2 pb-2 m-2 mb-0 rounded-3 border border-1" style="background-color: #0d6dfd; overflow-wrap: break-word;"></div>
</div>

<div id="message-system" class="d-flex justify-content-center">
      <div class="body p-3 pt-2 pb-2 m-2 mb-0 rounded-3 border border-1" style="background-color: grey; overflow-wrap: break-word; font-size: 12px"></div>
</div>





<span id="message-badge" class="badge rounded-pill bg-primary"><div class="body"></div></span>

<!-- container-fluid d-flex align-items-center justify-content-between border-bottom -->
  <div id="message_me" style="text-align:right;">
      <div class="p-3 pt-2 pb-2 m-2 mb-0 rounded-1 border border-1" style="background-color: white;  display:inline-block;">
        <small id="from" style=""></small>
          <div id="text" style="color: black">
          </div>
          <small id="chat-message-timestamp" style=""></small>
      </div>
  </div>

</div>