mysite/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    #path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),name="login"),
    path('logout/', auth_views.LogoutView.as_view(),name="logout"),
    path('signup/', views.signUp,name="signup"),
    path('<int:pk>/', views.AccountPage.as_view(), name='account_detail'),
    path("accept/<int:pk>/",views.AcceptContact.as_view(),name="accept_request"),
    path("reject/<int:pk>/",views.RejectContact.as_view(),name="reject_request"),
    path("delete/<int:pk>/",views.DeleteContact.as_view(),name="delete_contact"),
    path('', views.loginUser,name='login2'),
    path('login/', views.loginUser,name='login2'),
    path('search/', views.searchAccount,name='search'),


]

mysite/chat/urls.py
# chat/urls.py
from django.urls import path

from . import views
app_name = 'chat'

urlpatterns = [
    path('', views.meetings, name='meetings'),
    path('dev', views.dev, name='dev'),

]

mysite/mysite/urls.py
# mysite/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin

urlpatterns = [
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls',namespace="accounts")),
    path('', include('django.contrib.auth.urls')),
]

mysite/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.utils import timezone
User = get_user_model()

class ContactList(models.Model):
    user = models.OneToOneField(User, related_name='contactlist', on_delete=models.CASCADE)
    contacts = models.ManyToManyField(User, related_name='contacts', blank=True)


    def __str__(self):
        return self.user.username



    def is_contact(self, contact):
        if contact not in self.contacts.all():
            return False
        else:
            return True

    def add_contact(self, contact):
        if contact not in self.contacts.all():
            self.contacts.add(contact)
            self.save()

    def remove_contact(self, contact):
        if contact in self.contacts.all():
            self.contacts.remove(contact)
            self.save()

    def end_contact(self, contact):
        self.remove_contact(contact)
        ContactList.objects.get(user=contact).remove_contact(self.user)


    def is_mututal_contact(self, contact):
        if contact in self.contact.all():
            return True
        return False


class ContactRequest(models.Model):
    sender = models.ForeignKey(User, related_name='sender', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='contact_requests', on_delete=models.CASCADE)
    is_active = models.BooleanField(blank=True,null=False, default=False)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.sender.username

    def accept(self):

        receiver_contact_list = ContactList.objects.get(user=self.receiver)
        receiver_contact_list.add_contact(self.sender)

        sender_contact_list = ContactList.objects.get(user=self.sender)
        sender_contact_list.add_contact(self.receiver)

        self.is_active = True
        self.save()



class MainSession(models.Model):
    user = models.ForeignKey(User, related_name="main_user_sessions",on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=timezone.now,blank=True,null=True)





from django.db.models.signals import post_save
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer

def send_contact_request(sender,instance,**kwargs):

    channel_layer = get_channel_layer()
    receiver_layer = 'notifications_%s' % instance.receiver.username
    sender = instance.sender.username

    async_to_sync(channel_layer.group_send)(receiver_layer,{'type':'notify', 'message':'Friend request!' ,'sender': sender})


post_save.connect(send_contact_request,sender=ContactRequest)

mysite/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

    class Meta():
        fields = ('username','email','password1')
        model = get_user_model()

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Display name'
        self.fields['email'].label = 'Email address'

mysite/accounts/views.py
from django.contrib.auth import login, logout, authenticate
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect, HttpResponse
User = get_user_model()
from . import forms
from . import models

def signUp(request):
    form = forms.UserCreateForm()
    if request.method == "POST":
        form = forms.UserCreateForm(request.POST)
        if form.is_valid():
            user=form.save()
            user.save()
            models.ContactList.objects.create(user=user)
            models.MainSession.objects.create(user=user)


            return redirect('login')

    return render(request, 'accounts/signup.html', {'form':form})


def loginUser(request):


    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('chat:meetings'))

            else:
                return HttpResponse("Account not active")
        else:
            print('Someone tried to login and failed')
            print('Username: {} and Password: {}'.format(username,password))
            return HttpResponse("Invalid credentials")
    else:
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('chat:meetings'))
        else:
            return render(request,'accounts/login2.html')


class AcceptContact(generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        contact_request = models.ContactRequest.objects.get(pk=self.kwargs.get("pk"))
        contact_request.accept()
        return reverse("accounts:account_detail", kwargs={"pk":self.request.user.pk})

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


class RejectContact(generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        contact_request = models.ContactRequest.objects.get(pk=self.kwargs.get("pk"))
        contact_request.delete()
        return reverse("accounts:account_detail", kwargs={"pk":self.request.user.pk})

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


class DeleteContact(generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        contact_request = models.ContactRequest.objects.get(pk=self.kwargs.get("pk"))
        contact_request.delete()
        return reverse("accounts:account_detail", kwargs={"pk":self.request.user.pk})

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


def searchAccount(request):
    result = ''
    if request.method == "POST":
        search_query = request.POST.get('name')
        result = User.objects.filter(username__icontains=search_query)

    return render(request, 'accounts/search_contact.html',{'users':result})


class AccountPage(generic.DetailView):
    model = User
    template_name = 'accounts/user_detail.html'

mysite/accounts/templates/accounts/login.html
<!DOCTYPE html>
<div class="container">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-default" type="submit" value="Login">
  </form>
</div>

mysite/accounts/templates/accounts/login2.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>


      <div class="container col-xl-10 col-xxl-8 px-4 py-5">
      <div class="row align-items-center g-lg-5 py-5">
        <div class="col-lg-7 text-center text-lg-start">
          <h1 class="display-4 fw-bold lh-1 mb-3">Login here.</h1>
  
          <p class="col-lg-10 fs-4"><a href="{% url 'accounts:signup' %}">Create account</a> </p>
        </div>
        <div class="col-md-10 mx-auto col-lg-5">
          <form class="p-4 p-md-5 border rounded-3 bg-light" action="{% url 'accounts:login2' %}" method="POST">
            {% csrf_token %}


            <div class="form-floating mb-3">
              <input type="text" name="username" class="form-control" id="floatingInput" placeholder="name@example.com">
              <label for="username">Username:</label>
            </div>



            <div class="form-floating mb-3">
                <input type="password" name="password" class="form-control" placeholder="Password">
                <label for="password">Password:</label>
            </div>


            <input class="w-100 btn btn-lg btn-primary" type="submit" value="Login">




            <hr class="my-4">
            <small class="text-muted">By logging in, you agree to the terms of use.</small>
          </form>
        </div>
      </div>
    </div>



  </body>
</html>

mysite/accounts/templates/accounts/search_contact.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<h1>Search</h1>
<form action="{% url 'accounts:search' %}" method="POST">
  {% csrf_token %}

  <label for="username">Username:</label>
  <input type="text" name="name" value="Enter username">

  <input type="submit" name="" value="Search">

  {% for user in users %}
    <a href="{% url 'chat:start_meeting' pk=user.pk %}">  {{ user }}</a>
  {% endfor %}
</form>
</html>

mysite/accounts/templates/accounts/signup.html
<!DOCTYPE html>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
<div class="container">

  <h1>Sign up</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-default" type="submit" value="Sign up">

    <a href="{% url 'accounts:login2' %}">Login</a>

  </form>
</div>

mysite/accounts/templates/accounts/user_detail.html
{% extends 'base.html' %}

{% block body_block %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {{ user.username }}


    <h3>Contacts</h3>
    <ul>
    {% for contact in user.contactlist.contacts.all %}
      <li>
        <a href="{% url 'chat:start_meeting' pk=contact.pk %}">{{ contact }}</a>
      </li>
    {% endfor %}
    </ul>

    <h3>Invites</h3>
    <ul>
    {% for contact in user.contact_requests.all %}
      {% if contact.is_active %}

      {% else %}
      <li>{{ contact.sender.username }}
        <a href="{% url 'accounts:accept_request' pk=contact.pk %}">Accept</a>
        <a href="{% url 'accounts:reject_request' pk=contact.pk %}">Reject</a>
      </li>
      {% endif %}
    {% endfor %}
    </ul>

  </body>
</html>


{% endblock%}